version: '3'

networks:
  backend:
    driver: bridge

services:

  es:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9501:9501
    networks:
      - backend
    volumes:
      - ./es/easyswoole:/easyswoole:rw
    tty: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - backend
    volumes:
      - ./db/data/mysql:/var/lib/mysql:rw

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - backend
    volumes:
      - ./db/redis/:/data

  nginx:
    image: nginx
    restart: always
    depends_on:
      - es
    ports:
        - 8080:80
    networks:
        - backend
    volumes:
      - ./es/easyswoole:/easyswoole:rw
      - ./conf/conf.d:/etc/nginx/conf.d:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw

  frontdev:
    build:
      context: ./
      dockerfile: NodeDockerfile
    restart: always
    ports:
        - 8089:8080
    networks:
      - backend
    volumes:
      - ./es/easyswoole:/easyswoole:rw
      - ./front:/front:rw
    tty: true
